// <auto-generated />
using System;
using BisiparişVeriAltYapı;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BisiparişVeriAltYapı.Migrations
{
    [DbContext(typeof(BisiparişVeriBağlam))]
    [Migration("20191111180654_BisiparişMigration")]
    partial class BisiparişMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Değerlendirme.MüşteriDeğerleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<byte>("Değer")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Eleman")
                        .HasColumnType("tinyint");

                    b.Property<int>("ElemanId")
                        .HasColumnType("int");

                    b.Property<int>("MüşteriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Değerlemeler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriRestoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("MüşteriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestoranId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FavoriRestoranlar");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriYemek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("MüşteriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.Property<int>("YemekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FavoriYemekler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriÖğün", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("MüşteriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.Property<int>("ÖğünId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FavoriÖğünler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriİçecek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("MüşteriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.Property<int>("İçecekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favoriİçecekler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.Menü", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("YerId")
                        .HasColumnType("int");

                    b.Property<byte>("YerTür")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Menüler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.MenüÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Betimleme")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<float>("Fiyat")
                        .HasColumnType("real");

                    b.Property<int>("MenüId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tür")
                        .HasColumnType("int");

                    b.Property<int>("ÖğeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenülerÖğeler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.Restoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BankaHesabıIban")
                        .HasColumnType("nvarchar(34)")
                        .HasMaxLength(34);

                    b.Property<string>("BankaHesabıSahibi")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("Hizmetler")
                        .HasColumnType("bigint");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<byte>("OnayDurum")
                        .HasColumnType("tinyint");

                    b.Property<short>("Tür")
                        .HasColumnType("smallint");

                    b.Property<bool>("ÖzelSektörMü")
                        .HasColumnType("bit");

                    b.Property<int>("İletişimId")
                        .HasColumnType("int");

                    b.Property<string>("İsim")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Restoranlar");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.Öğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BarKod")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Betimleme")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Fiyat")
                        .HasColumnType("real");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<string>("TedarikçiBarKod")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TedarikçiKod")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Öğeler");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Öğe");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.Öğün", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Betimleme")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Öğünler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.ÖğünÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tür")
                        .HasColumnType("int");

                    b.Property<int>("ÖğeId")
                        .HasColumnType("int");

                    b.Property<int>("ÖğünId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ÖğünlerÖğeler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.EpostaAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<byte>("Kullanım")
                        .HasColumnType("tinyint");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("İletişimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EpostaAdresler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TemelKategoriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.Mahalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SemtId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.Müşteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BabaAdı")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<byte>("Cinsiyet")
                        .HasColumnType("tinyint");

                    b.Property<string>("DedeAdı")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DoğumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoğumYeriId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Fotoğraf")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("HayatDurum")
                        .HasColumnType("tinyint");

                    b.Property<string>("KimlikNumara")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<int?>("MilliyetId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SonGiriş")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("SosyalDurum")
                        .HasColumnType("tinyint");

                    b.Property<string>("SoyAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("İletişimId")
                        .HasColumnType("int");

                    b.Property<string>("İlkAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Müşteriler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.Semt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int?>("İlçeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("İlçeId");

                    b.ToTable("Semtler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.TelefonNumara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<byte>("Kullanım")
                        .HasColumnType("tinyint");

                    b.Property<string>("Numara")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("İletişimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TelefonNumaralar");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.VarlıkFotoğraf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Fotoğraf")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("VarlıkId")
                        .HasColumnType("int");

                    b.Property<byte>("VarlıkTip")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Fotoğraflar");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.VarlıkKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("VarlıkId")
                        .HasColumnType("int");

                    b.Property<byte>("VarlıkTür")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("VarlıklarKategoriler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.YerAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Betimleme")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("BinaNumerası")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<float?>("Boylam")
                        .HasColumnType("real");

                    b.Property<string>("CaddeSokakAdı")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<float?>("Enlem")
                        .HasColumnType("real");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("KöyId")
                        .HasColumnType("int");

                    b.Property<int?>("MahalleId")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SemtId")
                        .HasColumnType("int");

                    b.Property<int>("ÜlkeId")
                        .HasColumnType("int");

                    b.Property<int?>("İlId")
                        .HasColumnType("int");

                    b.Property<int?>("İlçeId")
                        .HasColumnType("int");

                    b.Property<int>("ŞehirId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("YerlerAdresler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.ÇalışmaZamanlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("HaftaGün")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Saate")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Saatten")
                        .HasColumnType("tinyint");

                    b.Property<int>("YerId")
                        .HasColumnType("int");

                    b.Property<byte>("YerTür")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("ÇalışmaZamanlamalar");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.Ülke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int?>("BaşkentId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<string>("İngilizceAdı")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Ülkeler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.İl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Plaka")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("İller");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.İletişim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookHesap")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<string>("TwitterkHesap")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("ViberNumara")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("WebsiteAdres")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("WhatsappNumara")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("YouTubeHesap")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("İnstagramHesap")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("İletişimler");

                    b.HasDiscriminator<string>("Discriminator").HasValue("İletişim");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.İlçe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int?>("İlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("İlçeler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.Şehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("ÜlkeId")
                        .HasColumnType("int");

                    b.Property<string>("İngilizceAdı")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Şehirler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Güvenlik.Kullanıcı", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<byte>("Cinsiyet")
                        .HasColumnType("tinyint");

                    b.Property<string>("Girişİsim")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonGirişTarihVeZaman")
                        .HasColumnType("datetime2");

                    b.Property<string>("İş")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Şifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Kullanıcılar");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<float>("Bakiye")
                        .HasColumnType("real");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("YerId")
                        .HasColumnType("int");

                    b.Property<byte>("YerTür")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Hesaplar");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MüşteriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaketMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MüşteriId");

                    b.ToTable("Sepetler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.SepetÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Miktar")
                        .HasColumnType("tinyint");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SepetId")
                        .HasColumnType("int");

                    b.Property<int>("Tür")
                        .HasColumnType("int");

                    b.Property<int>("ÖğeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SepetId");

                    b.ToTable("SepetlerÖğeler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.Sipariş", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("MüşteriId")
                        .HasColumnType("int");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaketMi")
                        .HasColumnType("bit");

                    b.Property<string>("QrKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("QrKodResim")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TeslimTarihVeZaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Siparişler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.SiparişÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Miktar")
                        .HasColumnType("tinyint");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiparişId")
                        .HasColumnType("int");

                    b.Property<int>("Tür")
                        .HasColumnType("int");

                    b.Property<int>("ÖğeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SiparişlerÖğeler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.İşlem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<float>("Değer")
                        .HasColumnType("real");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Tip")
                        .HasColumnType("tinyint");

                    b.Property<int>("YerId")
                        .HasColumnType("int");

                    b.Property<byte>("YerTür")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("İşlemler");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.VeriGünlüğü.Günlük", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Seviye")
                        .HasColumnType("tinyint");

                    b.Property<string>("Tarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Zaman")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("BilgiGünlük");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.Yemek", b =>
                {
                    b.HasBaseType("BisiparişÇekirdek.Valıklar.Erzak.Öğe");

                    b.HasDiscriminator().HasValue("Yemek");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Erzak.İçecek", b =>
                {
                    b.HasBaseType("BisiparişÇekirdek.Valıklar.Erzak.Öğe");

                    b.Property<byte>("Sıcaklık")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Tür")
                        .HasColumnType("tinyint");

                    b.HasDiscriminator().HasValue("İçecek");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.İşyeriİletişim", b =>
                {
                    b.HasBaseType("BisiparişÇekirdek.Valıklar.Esansiyel.İletişim");

                    b.HasDiscriminator().HasValue("İşyeriİletişim");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Esansiyel.Semt", b =>
                {
                    b.HasOne("BisiparişÇekirdek.Valıklar.Esansiyel.İlçe", "İlçe")
                        .WithMany()
                        .HasForeignKey("İlçeId");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.Sepet", b =>
                {
                    b.HasOne("BisiparişÇekirdek.Valıklar.Esansiyel.Müşteri", "Müşteri")
                        .WithMany()
                        .HasForeignKey("MüşteriId");
                });

            modelBuilder.Entity("BisiparişÇekirdek.Valıklar.Muhasebe.SepetÖğe", b =>
                {
                    b.HasOne("BisiparişÇekirdek.Valıklar.Muhasebe.Sepet", null)
                        .WithMany("Öğeler")
                        .HasForeignKey("SepetId");
                });
#pragma warning restore 612, 618
        }
    }
}
