// <auto-generated />
using System;
using HazırlaVeriAltYapı;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HazırlaVeriAltYapı.Migrations
{
    [DbContext(typeof(HazırlaVeriBağlam))]
    [Migration("20191127142711_MigrationNumber1")]
    partial class MigrationNumber1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Değerlendirme.MüşteriDeğerleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte?>("Değer")
                        .HasColumnType("smallint");

                    b.Property<int>("MüşteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VarlıkId")
                        .HasColumnType("integer");

                    b.Property<byte>("VarlıkTip")
                        .HasColumnType("smallint");

                    b.Property<string>("Yorum")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Değerlemeler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriRestoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MüşteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RestoranId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("FavoriRestoranlar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriYemek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MüşteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("YemekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FavoriYemekler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriÖğün", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MüşteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ÖğünId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FavoriÖğünler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Değerlendirme.MüşteriFavoriİçecek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MüşteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("İçecekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Favoriİçecekler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.Menü", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Onaylandı")
                        .HasColumnType("boolean");

                    b.Property<string>("ReddetSebebi")
                        .HasColumnType("text");

                    b.Property<int>("RestoranId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Menüler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.MenüÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.Property<string>("Betimleme")
                        .HasColumnType("character varying(75)")
                        .HasMaxLength(75);

                    b.Property<float>("Fiyat")
                        .HasColumnType("real");

                    b.Property<int>("MenüId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<byte>("Tür")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("MenülerÖğeler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.Restoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BankaHesabıIban")
                        .HasColumnType("character varying(34)")
                        .HasMaxLength(34);

                    b.Property<string>("BankaHesabıSahibi")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<long>("Hizmetler")
                        .HasColumnType("bigint");

                    b.Property<int>("Mutfaklar")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("OnayDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("ReddetSebebi")
                        .HasColumnType("text");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<short>("Tür")
                        .HasColumnType("smallint");

                    b.Property<bool>("ÖzelSektörMü")
                        .HasColumnType("boolean");

                    b.Property<int>("İletişimId")
                        .HasColumnType("integer");

                    b.Property<string>("İsim")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Restoranlar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.Öğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(75)")
                        .HasMaxLength(75);

                    b.Property<string>("BarKod")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Betimleme")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Fiyat")
                        .HasColumnType("real");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("TedarikçiBarKod")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TedarikçiKod")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Öğeler");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Öğe");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.Öğün", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Betimleme")
                        .HasColumnType("character varying(300)")
                        .HasMaxLength(300);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Öğünler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.ÖğünÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("Tür")
                        .HasColumnType("integer");

                    b.Property<int>("ÖğeId")
                        .HasColumnType("integer");

                    b.Property<int>("ÖğünId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ÖğünlerÖğeler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.EpostaAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<byte>("Kullanım")
                        .HasColumnType("smallint");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("İletişimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EpostaAdresler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RestoranId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int?>("TemelKategoriId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Mahalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SemtId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Müşteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BabaAdı")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<byte>("Cinsiyet")
                        .HasColumnType("smallint");

                    b.Property<string>("DedeAdı")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DoğumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DoğumYeriId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Fotoğraf")
                        .HasColumnType("bytea");

                    b.Property<byte>("HayatDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("KimlikNumara")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<int?>("MilliyetId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SonGiriş")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte?>("SosyalDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("SoyAdı")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("İletişimId")
                        .HasColumnType("integer");

                    b.Property<string>("İlkAdı")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Müşteriler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Semt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int?>("İlçeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("İlçeId");

                    b.ToTable("Semtler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Sistemİşlem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("KullanıcıId")
                        .HasColumnType("integer");

                    b.Property<string>("Tarih")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<byte>("Tip")
                        .HasColumnType("smallint");

                    b.Property<string>("Zaman")
                        .IsRequired()
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.Property<int>("ÖğeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sistemİşlemler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.TelefonNumara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("Kullanım")
                        .HasColumnType("smallint");

                    b.Property<string>("Numara")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("İletişimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelefonNumaralar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.VarlıkFotoğraf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Fotoğraf")
                        .HasColumnType("bytea");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("VarlıkId")
                        .HasColumnType("integer");

                    b.Property<byte>("VarlıkTip")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Fotoğraflar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.VarlıkKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("VarlıkId")
                        .HasColumnType("integer");

                    b.Property<byte>("VarlıkTür")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("VarlıklarKategoriler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.YerAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Betimleme")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<string>("BinaNumerası")
                        .HasColumnType("character varying(7)")
                        .HasMaxLength(7);

                    b.Property<float?>("Boylam")
                        .HasColumnType("real");

                    b.Property<string>("CaddeSokakAdı")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<float?>("Enlem")
                        .HasColumnType("real");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("KöyId")
                        .HasColumnType("integer");

                    b.Property<int?>("MahalleId")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SemtId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("ÜlkeId")
                        .HasColumnType("integer");

                    b.Property<int?>("İlId")
                        .HasColumnType("integer");

                    b.Property<int?>("İlçeId")
                        .HasColumnType("integer");

                    b.Property<int>("ŞehirId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("YerlerAdresler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.ÇalışmaZamanlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("HaftaGün")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Saate")
                        .IsRequired()
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Saatten")
                        .IsRequired()
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("İşletmeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ÇalışmaZamanlamalar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Ülke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("BaşkentId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("İngilizceAdı")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Ülkeler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.İl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("Plaka")
                        .HasColumnType("smallint");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("İller");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.İletişim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdresId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookHesap")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("TwitterkHesap")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("ViberNumara")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("WebsiteAdres")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("WhatsappNumara")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("YouTubeHesap")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("İnstagramHesap")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("İletişimler");

                    b.HasDiscriminator<string>("Discriminator").HasValue("İletişim");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.İlçe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int?>("İlId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("İlçeler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Şehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("ÜlkeId")
                        .HasColumnType("integer");

                    b.Property<string>("İngilizceAdı")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Şehirler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Güvenlik.Kullanıcı", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<byte>("Cinsiyet")
                        .HasColumnType("smallint");

                    b.Property<string>("Girişİsim")
                        .IsRequired()
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("KaldırmaSebebi")
                        .HasColumnType("text");

                    b.Property<string>("KarmaŞifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Pozisyon")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SonGirişTarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Kullanıcılar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Güvenlik.KullanıcıRestoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("KullanıcıId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RestoranId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("KullanıcılarRestoranlar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("Bakiye")
                        .HasColumnType("real");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("YerId")
                        .HasColumnType("integer");

                    b.Property<byte>("YerTür")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Hesaplar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.Kupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("GeçerlilikSüresi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("Kıymet")
                        .HasColumnType("real");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<byte>("İndirimOranı")
                        .HasColumnType("smallint");

                    b.Property<string>("Şart")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kuponlar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.Promosyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Promosyonlar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("text");

                    b.Property<bool?>("DışMekanSeçimiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Hazırlanacağı")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("KuponId")
                        .HasColumnType("integer");

                    b.Property<string>("MasaSayısı")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<int>("MüşteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("PaketMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("PromosyonId")
                        .HasColumnType("integer");

                    b.Property<int>("RestoranId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("ToplamFiyat")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Sepetler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.SepetÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("text");

                    b.Property<byte>("Miktar")
                        .HasColumnType("smallint");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<float>("TekFiyat")
                        .HasColumnType("real");

                    b.Property<float>("ToplamFiyat")
                        .HasColumnType("real");

                    b.Property<byte>("Tür")
                        .HasColumnType("smallint");

                    b.Property<int>("ÖğeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SepetlerÖğeler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.Sipariş", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("text");

                    b.Property<byte>("Durum")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GelmeZamanı")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte?>("MasaAdedi")
                        .HasColumnType("smallint");

                    b.Property<int>("MüşteriId")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("PaketMi")
                        .HasColumnType("boolean");

                    b.Property<string>("QrKod")
                        .HasColumnType("text");

                    b.Property<byte[]>("QrKodResim")
                        .HasColumnType("bytea");

                    b.Property<int>("RestoranId")
                        .HasColumnType("integer");

                    b.Property<int>("SepetId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TeslimTarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("İptalSebebi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Siparişler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.SiparişÖğe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Miktar")
                        .HasColumnType("smallint");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SiparişId")
                        .HasColumnType("integer");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<byte>("Tür")
                        .HasColumnType("smallint");

                    b.Property<int>("ÖğeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SiparişlerÖğeler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Muhasebe.İşlem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("Değer")
                        .HasColumnType("real");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("Tip")
                        .HasColumnType("smallint");

                    b.Property<int>("YerId")
                        .HasColumnType("integer");

                    b.Property<byte>("YerTür")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("İşlemler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.SistemYönetim.YardımYanıt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("Yanıt")
                        .HasColumnType("text");

                    b.Property<DateTime>("İslemTarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("İstekId")
                        .HasColumnType("integer");

                    b.Property<string>("İçNotlar")
                        .HasColumnType("text");

                    b.Property<int>("İşlemciId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("YardımYanıtlar");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.SistemYönetim.Yardımİstek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ayrıntılar")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("OluşturuKimsiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Oluşturulduğunda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("SistemDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("İstekSahibiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("İstekTarihVeZaman")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Yardımİstekler");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.VeriGünlüğü.Günlük", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Seviye")
                        .HasColumnType("smallint");

                    b.Property<string>("Tarih")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Zaman")
                        .IsRequired()
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("BilgiGünlük");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.Yemek", b =>
                {
                    b.HasBaseType("HazırlaÇekirdek.Valıklar.Erzak.Öğe");

                    b.HasDiscriminator().HasValue("Yemek");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Erzak.İçecek", b =>
                {
                    b.HasBaseType("HazırlaÇekirdek.Valıklar.Erzak.Öğe");

                    b.Property<byte>("Sıcaklık")
                        .HasColumnType("smallint");

                    b.Property<byte>("Tür")
                        .HasColumnType("smallint");

                    b.HasDiscriminator().HasValue("İçecek");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.İşyeriİletişim", b =>
                {
                    b.HasBaseType("HazırlaÇekirdek.Valıklar.Esansiyel.İletişim");

                    b.HasDiscriminator().HasValue("İşyeriİletişim");
                });

            modelBuilder.Entity("HazırlaÇekirdek.Valıklar.Esansiyel.Semt", b =>
                {
                    b.HasOne("HazırlaÇekirdek.Valıklar.Esansiyel.İlçe", "İlçe")
                        .WithMany()
                        .HasForeignKey("İlçeId");
                });
#pragma warning restore 612, 618
        }
    }
}
